logging:
  level:
    org.springframework.data.r2dbc: DEBUG
spring:
  application:
    name: demo
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
#        include: "*"
  endpoint:
    health:
#      show-details: always
      probes:
        enabled: true

server:
  port: ${PORT:3333}